CREATE TABLE [dbo].[OrdenDePedido] (
    [OrdenDePedidoId]               INT             IDENTITY (1, 1) NOT NULL,
    [NumeroPedido]                  INT             NOT NULL,
    [ClienteId]                     INT             NOT NULL,
    [FechaHoraPedido]               DATETIME        NOT NULL,
    [RetiraPersonalmente]           BIT             DEFAULT ((0)) NOT NULL,
    [EntregaEstimadaFecha]          DATE            NULL,
    [EntregaEstimadaRangoHorarioId] INT             NULL,
    [EntregaDomicilio]              NVARCHAR (50)   NULL,
    [EntregaEntreCalles]            NVARCHAR (50)   NULL,
    [EntregaLocalidad]              NVARCHAR (50)   NULL,
    [EntregaTelefono1]              NVARCHAR (30)   NULL,
    [EntregaTelefono2]              NVARCHAR (30)   NULL,
    [EntregaObservaciones]          NVARCHAR (200)  NULL,
    [UsuarioId]                     INT             NULL,
    [NumeroRemito]                  NVARCHAR (20)   NULL,
    [VentaId]                       INT             NULL,
    [Activo]                        BIT             NULL,
    [Observaciones]                 NVARCHAR (200)  NULL,
    [PreparacionFechaHoraInicio]    DATETIME        NULL,
    [PreparacionFechaHoraFin]       DATETIME        NULL,
    [PreparacionUsuarioId]          INT             NULL,
    [DespachoFechaHora]             DATETIME        NULL,
    [DespachoUsuarioId]             INT             NULL,
    [MarcoEntregaFechaHora]         DATETIME        NULL,
    [MarcoEntregaUsuarioId]         INT             NULL,
    [PesoTotalEnGramos]             INT             NOT NULL,
    [MontoTotal]                    DECIMAL (18, 2) NULL,
    [DespachoTransporteId]          INT             NULL,
    [PagoReferencia]                NVARCHAR (50)   NULL,
    [MedioDePago]                   NVARCHAR (30)   NULL,
    PRIMARY KEY CLUSTERED ([OrdenDePedidoId] ASC),
    FOREIGN KEY ([ClienteId]) REFERENCES [dbo].[Cliente] ([ClienteId])
);

